#!/bin/sh

if test -d ./.git; then
	:
else
	echo "$0: No git repository here"
	exit 1
fi

project=`basename $(pwd)`
user=`id -un`


sigrand=ssh://git@sigrand.ru/$project.git
   live=ssh://live.1nsk.ru/home/df/siggit/$project.git
 telana=ssh://xsited@git.xwire.com/www/xwire.com/subdomains/git/$project.git

case $user in
        df) repos="$sigrand $live $telana";;
    xsited) repos="$telana";;
         *) repos="$sigrand";;
esac

echo
for r in $repos; do
	echo "======== $r"
	git push "$@" $r
done
echo
